/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parqueo;

import javax.swing.JOptionPane;

/**
 *
 * @author Vinni
 */
public class Ventana extends javax.swing.JFrame {
    private Parqueadero p ;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        p = new Parqueadero();
        initComponents();
        this.consultaDisponiblesCarro();
        this.consultaDisponiblesMoto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cjPlaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btAddMoto = new javax.swing.JButton();
        btAddCarro = new javax.swing.JButton();
        btRetVeh = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tmCarro = new javax.swing.JLabel();
        tmMoto = new javax.swing.JLabel();
        btRetiraCarro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PARQUEADERO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 150, 30);

        cjPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(cjPlaca);
        cjPlaca.setBounds(180, 80, 100, 30);

        jLabel2.setText("PLACA :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 80, 50, 20);

        btAddMoto.setText("ADICIONAR MOTO");
        btAddMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddMotoActionPerformed(evt);
            }
        });
        getContentPane().add(btAddMoto);
        btAddMoto.setBounds(340, 63, 160, 30);

        btAddCarro.setText("ADICIONAR CARRO");
        btAddCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddCarroActionPerformed(evt);
            }
        });
        getContentPane().add(btAddCarro);
        btAddCarro.setBounds(340, 103, 160, 30);

        btRetVeh.setText("RETIRAR MOTO");
        btRetVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetVehActionPerformed(evt);
            }
        });
        getContentPane().add(btRetVeh);
        btRetVeh.setBounds(340, 140, 160, 30);

        btSalir.setText("SALIR");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir);
        btSalir.setBounds(401, 330, 100, 23);

        jLabel3.setText("CUPOS DISPONIBLES CARROS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 300, 200, 14);

        jLabel4.setText("CUPOS DISPONIBLES MOTOS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 320, 200, 14);

        tmCarro.setText("18");
        getContentPane().add(tmCarro);
        tmCarro.setBounds(250, 300, 20, 14);

        tmMoto.setText("10");
        getContentPane().add(tmMoto);
        tmMoto.setBounds(250, 320, 20, 14);

        btRetiraCarro.setText("RETIRAR CARRO");
        btRetiraCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRetiraCarroActionPerformed(evt);
            }
        });
        getContentPane().add(btRetiraCarro);
        btRetiraCarro.setBounds(340, 180, 160, 30);

        setSize(new java.awt.Dimension(559, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cjPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjPlacaActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        this.salir();
    }//GEN-LAST:event_btSalirActionPerformed

    private void btAddMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddMotoActionPerformed
        this.addMoto();
    }//GEN-LAST:event_btAddMotoActionPerformed

    private void btAddCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddCarroActionPerformed
        this.addCarro();
    }//GEN-LAST:event_btAddCarroActionPerformed

    private void btRetVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetVehActionPerformed
        this.salidaVehiculo();
    }//GEN-LAST:event_btRetVehActionPerformed

    private void btRetiraCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRetiraCarroActionPerformed
        // TODO add your handling code here:
        this.retiraCarro();
    }//GEN-LAST:event_btRetiraCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    /**
     * click al boton salir
     */
    private void salir(){
        System.exit(0);
    }
    /**
     * click al boton salir
     */
    private void addMoto(){
        String laplaca = cjPlaca.getText();
        Vehiculo moto = new Vehiculo(laplaca, "MOTO");
        
        boolean inserta = p.addMoto(moto);
        if (inserta){
            JOptionPane.showMessageDialog(this, "Adiciono la moto");
            this.consultaDisponiblesMoto();
        }else{
            JOptionPane.showMessageDialog(this, "No inserto, ya se encuentra");
        }
        
    }
    /**
     * click al boton salir
     */
    private void addCarro(){
        String laplaca = cjPlaca.getText();
        Vehiculo carro = new Vehiculo(laplaca, "CARRO");
        boolean inserta = p.addCarro(carro);
        if (inserta){
            JOptionPane.showMessageDialog(this, "Adiciono el carro");
            this.consultaDisponiblesCarro();
        }else{
            JOptionPane.showMessageDialog(this, "No inserto, ya se encuentra");
        }
    }
    /**
     * 
     */
    private void salidaVehiculo(){
        String laplaca = cjPlaca.getText();
        long valorpagar = p.salir(laplaca, "MOTO");
        if (valorpagar>=0){
            JOptionPane.showMessageDialog(this, "Debe pagar $"+valorpagar);
            this.consultaDisponiblesMoto();
        }else{
            JOptionPane.showMessageDialog(this, "No existe.");
        }
        
    }
    private void retiraCarro(){
        String laplaca = cjPlaca.getText();
        long valorpagar = p.salir(laplaca, "CARRO");
        if (valorpagar>=0){
            JOptionPane.showMessageDialog(this, "Debe pagar $"+valorpagar);
            this.consultaDisponiblesCarro();
        }else{
            JOptionPane.showMessageDialog(this, "No existe.");
        }
        
    }
    private void consultaDisponiblesMoto (){
        int cupoM = p.cuposDisponiblesMoto();
        this.tmMoto.setText(""+cupoM);
        
    }
    private void consultaDisponiblesCarro (){
        int cupoC = p.cuposDisponiblesCarro();
        this.tmCarro.setText(""+cupoC);
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddCarro;
    private javax.swing.JButton btAddMoto;
    private javax.swing.JButton btRetVeh;
    private javax.swing.JButton btRetiraCarro;
    private javax.swing.JButton btSalir;
    private javax.swing.JTextField cjPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel tmCarro;
    private javax.swing.JLabel tmMoto;
    // End of variables declaration//GEN-END:variables
}
