/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package directoriocontac;

import javax.swing.JOptionPane;

/**
 *
 * @author Vinni
 */
public class Ventana extends javax.swing.JFrame {
    private Libreta milibreta = new Libreta();

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
        this.imprimeContactos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cjNombre = new javax.swing.JTextField();
        cjApellido = new javax.swing.JTextField();
        cjTelefono = new javax.swing.JTextField();
        cjEmpresa = new javax.swing.JTextField();
        cjCorreo = new javax.swing.JTextField();
        chFavorito = new javax.swing.JCheckBox();
        btAdicionar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cjContactos = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Contactos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 10, 90, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 49, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 90, 70, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 120, 52, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Empresa");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 150, 80, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Correo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 180, 60, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Favorito");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 210, 60, 17);

        cjNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cjNombre);
        cjNombre.setBounds(130, 60, 160, 23);

        cjApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cjApellido);
        cjApellido.setBounds(130, 90, 160, 23);

        cjTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cjTelefono);
        cjTelefono.setBounds(130, 120, 160, 23);

        cjEmpresa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cjEmpresa);
        cjEmpresa.setBounds(130, 150, 160, 23);

        cjCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(cjCorreo);
        cjCorreo.setBounds(130, 180, 160, 23);

        chFavorito.setText("SI");
        chFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chFavoritoActionPerformed(evt);
            }
        });
        getContentPane().add(chFavorito);
        chFavorito.setBounds(130, 210, 80, 23);

        btAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btAdicionar);
        btAdicionar.setBounds(40, 250, 100, 25);

        btSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir);
        btSalir.setBounds(560, 290, 100, 25);

        cjContactos.setColumns(20);
        cjContactos.setRows(5);
        jScrollPane1.setViewportView(cjContactos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(316, 30, 320, 250);

        jLabel8.setBackground(new java.awt.Color(0, 0, 153));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Libreta");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 10, 60, 22);

        setSize(new java.awt.Dimension(693, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chFavoritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chFavoritoActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        this.salir();
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        this.adicionarContacto();
    }//GEN-LAST:event_btAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    private void adicionarContacto(){
        String nombre = cjNombre.getText();
        String apellido = cjApellido.getText();
        String correo = cjCorreo.getText();
        String empresa = cjEmpresa.getText();
        String telefonoS = cjTelefono.getText();
        Integer telefono = Integer.parseInt(telefonoS);

        Contacto cnuevo = new Contacto(nombre, apellido, telefono);
        cnuevo.setEmpresa(empresa);
        cnuevo.setCorreo(correo);
        cnuevo.setFavorito(this.chFavorito.isSelected());
        
        
        if (milibreta.adicionContacto(cnuevo)){
            JOptionPane.showMessageDialog(this, "Creo a "+cnuevo.getNombre());
        }else{
            JOptionPane.showMessageDialog(this, "No creo el contacto");
        }
        this.imprimeContactos();
        
        
    }
    private void imprimeContactos(){
        this.cjContactos.setText("");
        this.cjContactos.append("CONTACTOS - - -\n");
        this.cjContactos.append("FAV\tNOMBRE\t APELLIDO\t TELEFONO\n");
        //
        for (Contacto contacto : this.milibreta.listar()) {
            String fav = contacto.isFavorito()?"X":" ";
              this.cjContactos.append(fav+"\t"+contacto.getNombre()+"\t"+
                      contacto.getApellido()+"\t "+contacto.getTelefono()+"\n");

            //this.cjContactos.append(contacto.toString()+"\n");
        }
    }
            
    private void consultarContacto(){
        
    }
    private void consultarOrdenadoContacto(){
        
    }
    private void editarContacto(){
        
    }
    private void borrarContacto(){
        
    }
    private void salir(){
        System.exit(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btSalir;
    private javax.swing.JCheckBox chFavorito;
    private javax.swing.JTextField cjApellido;
    private javax.swing.JTextArea cjContactos;
    private javax.swing.JTextField cjCorreo;
    private javax.swing.JTextField cjEmpresa;
    private javax.swing.JTextField cjNombre;
    private javax.swing.JTextField cjTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
