/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package llamadas;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinni
 */
public class VentanaLlamadas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLlamadas
     */
    public VentanaLlamadas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cjNorigen = new javax.swing.JTextField();
        cjNdestino = new javax.swing.JTextField();
        cjFecha = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        cjTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cjMinutos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Numero origen");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 30, 130, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Numero destino");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 60, 100, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("tipo origen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 90, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 130, 80, 15);

        cjNorigen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(cjNorigen);
        cjNorigen.setBounds(200, 30, 110, 21);

        cjNdestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(cjNdestino);
        cjNdestino.setBounds(200, 60, 110, 21);

        cjFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(cjFecha);
        cjFecha.setBounds(200, 130, 110, 21);

        btGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btGuardar);
        btGuardar.setBounds(260, 200, 130, 23);

        cjTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cjTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIJO", "CELULAR" }));
        getContentPane().add(cjTipo);
        cjTipo.setBounds(200, 100, 110, 21);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("minutos");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 160, 120, 15);

        cjMinutos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(cjMinutos);
        cjMinutos.setBounds(200, 160, 110, 21);

        setSize(new java.awt.Dimension(423, 279));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
        this.guardar();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void guardar(){
        Historial histo = new Historial();
        Long nuOrigen = Long.parseLong(cjNorigen.getText());
        Long nuDestino = Long.parseLong(cjNdestino.getText());
        String fecha = cjFecha.getText();
        int minutos = Integer.parseInt(cjMinutos.getText());
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy"); 
        Date lafecha = null;
        try {
            lafecha = formato.parse(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(VentanaLlamadas.class.getName()).log(Level.SEVERE, null, ex);
        }
        Llamada llam = new Llamada(0L, nuOrigen, nuDestino, cjTipo.getSelectedItem().toString(), 
                lafecha, minutos);
        int rta = histo.crearLlamada(llam);
        if (rta > 0){
            JOptionPane.showMessageDialog(this,  "Se registró","Importante", JOptionPane.INFORMATION_MESSAGE);
            
        }else{
            JOptionPane.showMessageDialog(this,  "No se registró","Importante", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLlamadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JTextField cjFecha;
    private javax.swing.JTextField cjMinutos;
    private javax.swing.JTextField cjNdestino;
    private javax.swing.JTextField cjNorigen;
    private javax.swing.JComboBox<String> cjTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
